---
label: Products Page
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: layout
  label: layout
- type: text
  name: slug
  label: slug
- type: text
  name: url
  label: url
